[project]
name = "nano_assistant"
version = "1.0.0"
readme = "README.md"
authors = [
    { name = "Jordon Scott", email = "jordonsc@gmail.com" }
]
requires-python = ">=3.10"

dependencies = [
    "homeassistant >= 2024.12.0",
    "nanoleafapi >= 2.1.2",
]
